### ISSUE TITLE
E1 error when adding to thingset node

### ISSUE THREAD

**Issue by Ananyaaynana** [ThingSet/thingset-node-c#8]
Issue Description:
I am attempting to add a total of 13 parameters under the Conf node in Thingset. So far, I have successfully incorporated 10 parameters without any issues. However, when I try to add the 11th parameter, I encounter an 'E1' error code when executing the 'thingset ?Conf' command in the terminal. The 'E1' error is associated with the message /**< Error code: Response not fitting into buffer */.

Details:

    Parameter Definition:
        Parameter ID: APP_ID_CONF_DIS_OVERCURRENT_LATCH_RECOVERY_CURRENT
        Parameter Name: sDisOvercurrentLatchRecovery_mA
        Type: INT16
        Variable: &bms.conf.dis_oc_latch_recovery_mA
        Access: THINGSET_ANY_R | THINGSET_ANY_W
        Subset: TS_SUBSET_NVM

Error:
Upon adding the 11th parameter, attempting to query 'thingset ?Conf' results in an 'E1' error code, indicating that the response is not fitting into the buffer.

Code Snippet:
`THINGSET_ADD_ITEM_INT16(APP_ID_CONF, APP_ID_CONF_DIS_OVERCURRENT_LATCH_RECOVERY_CURRENT, "sDisOvercurrentLatchRecovery_mA", &bms.conf.dis_oc_latch_recovery_mA, THINGSET_ANY_R | THINGSET_ANY_W, TS_SUBSET_NVM);`

How do I incorporate all the 13 parameters successfully?

Thingset Version: Commit number: 0f97b99, Branch: manifest-rev
Platform/Environment: BMS_C1 firmware, commit: cb89c75

**Comment by martinjaeger** [comment]
Most probably you have to increase the buffer via Kconfig: https://github.com/ThingSet/thingset-zephyr-sdk/blob/b0885e333a11893b6851fa555e7391b786a8b4f4/Kconfig#L73

**Comment by Ananyaaynana** [comment]
Changing the Kconfig worked. Thank you.
